@extends('layouts.admin.master')
@section('title','Break Planning & Compliance')
@section('css')
<style>
.compliance-page{--ink:#17313b;--muted:#6d7d84;--line:#dce5e8;--red:#a6402b;--green:#176b5b;max-width:1500px;color:var(--ink)}.compliance-hero{background:#173f48;color:#fff;border-radius:14px;padding:22px 26px;display:flex;align-items:center;justify-content:space-between;gap:18px;box-shadow:0 16px 34px rgba(22,60,70,.16)}.compliance-hero h1{font-size:1.55rem;font-weight:850;margin:0}.compliance-hero p{margin:5px 0 0;color:#cce0df}.compliance-grid{display:grid;grid-template-columns:350px 1fr;gap:18px;margin-top:18px}.compliance-panel{background:#fff;border:1px solid var(--line);border-radius:12px;box-shadow:0 5px 18px rgba(23,49,59,.06)}.panel-head{padding:15px 18px;border-bottom:1px solid var(--line);font-weight:850}.panel-body{padding:16px}.rule-card{padding:14px;border:1px solid var(--line);border-radius:9px;margin-bottom:12px}.rule-card:last-child{margin-bottom:0}.audit-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:14px}.audit-stat{border:1px solid var(--line);border-radius:9px;padding:10px;background:#f8fafb}.audit-stat span{display:block;font-size:.66rem;text-transform:uppercase;color:var(--muted);font-weight:850}.audit-stat strong{font-size:1.35rem}.shift-audit{border:1px solid var(--line);border-radius:10px;margin-bottom:9px;overflow:hidden}.shift-audit.is-warning{border-left:5px solid #d35a38}.shift-audit-head{display:flex;justify-content:space-between;gap:12px;padding:12px 14px;background:#fbfcfc}.shift-audit-title{font-weight:850}.shift-audit-meta{font-size:.75rem;color:var(--muted)}.warning-chip,.break-chip{display:inline-flex;align-items:center;gap:4px;border-radius:999px;padding:3px 7px;font-size:.68rem;font-weight:850}.warning-chip{background:#fff0ec;color:var(--red)}.break-chip{background:#edf8f4;color:var(--green)}.shift-audit-body{padding:12px 14px;border-top:1px solid var(--line)}.break-form{display:grid;grid-template-columns:130px 90px 90px 1fr auto;gap:7px;align-items:end}@media(max-width:1050px){.compliance-grid{grid-template-columns:1fr}.audit-summary{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.compliance-hero{align-items:flex-start;flex-direction:column}.break-form{grid-template-columns:1fr 1fr}.break-form button{grid-column:1/-1}.audit-summary{grid-template-columns:1fr 1fr}}
</style>
@endsection
@section('content')
<div class="container-fluid compliance-page">
<header class="compliance-hero"><div><h1>Break planning & compliance</h1><p>Review the week before publishing and resolve preventable roster warnings.</p></div><div class="d-flex align-items-center"><a class="btn btn-light btn-sm mr-2" href="{{ route('manager.schedule-compliance.index',['week'=>$weekStart->copy()->subWeek()->toDateString()]) }}"><i class="fas fa-chevron-left"></i></a><strong>{{ $weekStart->format('d-m-Y') }} – {{ $weekStart->copy()->endOfWeek()->format('d-m-Y') }}</strong><a class="btn btn-light btn-sm ml-2" href="{{ route('manager.schedule-compliance.index',['week'=>$weekStart->copy()->addWeek()->toDateString()]) }}"><i class="fas fa-chevron-right"></i></a><a class="btn btn-outline-light btn-sm ml-2" href="{{ route('manager.shifts.create',['month'=>$weekStart->format('Y-m'),'day'=>$weekStart->toDateString()]) }}">Schedule</a></div></header>
@if(session('success'))<div class="alert alert-success mt-3">{{ session('success') }}</div>@endif @if($errors->has('schedule_compliance'))<div class="alert alert-danger mt-3">{{ $errors->first('schedule_compliance') }}</div>@endif @if($errors->any()&&!$errors->has('schedule_compliance'))<div class="alert alert-danger mt-3">{{ $errors->first() }}</div>@endif @if($odooPlanningError)<div class="alert alert-warning mt-3">{{ $odooPlanningError }}</div>@endif
<div class="compliance-grid">
<aside class="compliance-panel"><div class="panel-head">Rules by location</div><div class="panel-body">
@forelse($companies as $company) @php $rule=$rules->firstWhere('company_id',$company['id']); @endphp
<form class="rule-card" method="POST" action="{{ route('manager.schedule-compliance.rules') }}">@csrf<input type="hidden" name="week" value="{{ $weekStart->toDateString() }}"><input type="hidden" name="company_id" value="{{ $company['id'] }}"><strong>{{ $company['name'] }}</strong><div class="form-group mt-2"><label class="small">Break required after</label><div class="input-group input-group-sm"><input class="form-control" type="number" name="break_required_after_minutes" min="60" max="1440" value="{{ $rule->break_required_after_minutes??300 }}" required><div class="input-group-append"><span class="input-group-text">min</span></div></div></div><div class="form-group"><label class="small">Minimum break</label><div class="input-group input-group-sm"><input class="form-control" type="number" name="minimum_break_minutes" min="0" max="240" value="{{ $rule->minimum_break_minutes??30 }}" required><div class="input-group-append"><span class="input-group-text">min</span></div></div></div><div class="form-group"><label class="small">Maximum shift</label><div class="input-group input-group-sm"><input class="form-control" type="number" name="maximum_shift_minutes" min="60" max="1440" value="{{ $rule->maximum_shift_minutes??720 }}" required><div class="input-group-append"><span class="input-group-text">min</span></div></div></div><div class="form-group"><label class="small">Minimum rest between shifts</label><div class="input-group input-group-sm"><input class="form-control" type="number" name="minimum_rest_minutes" min="0" max="2880" value="{{ $rule->minimum_rest_minutes??600 }}" required><div class="input-group-append"><span class="input-group-text">min</span></div></div></div><label class="small"><input type="checkbox" name="is_enabled" value="1" {{ !$rule||$rule->is_enabled?'checked':'' }}> Enable warnings</label><button class="btn btn-outline-success btn-sm btn-block mt-2">Save rules</button></form>
@empty <div class="text-muted">No Odoo locations available.</div> @endforelse
</div></aside>
<main class="compliance-panel"><div class="panel-head">Weekly audit</div><div class="panel-body">
@php $summary=$audit['summary']; @endphp<div class="audit-summary"><div class="audit-stat"><span>Warning shifts</span><strong>{{ $summary['violation_shifts'] }}</strong></div><div class="audit-stat"><span>Missing breaks</span><strong>{{ $summary['missing_breaks'] }}</strong></div><div class="audit-stat"><span>Short rest</span><strong>{{ $summary['short_rest'] }}</strong></div><div class="audit-stat"><span>Planned breaks</span><strong>{{ $summary['planned_breaks'] }}</strong></div></div>
@forelse($audit['shifts'] as $shift)
<article class="shift-audit {{ !empty($shift['compliance_warnings'])?'is-warning':'' }}"><div class="shift-audit-head"><div><div class="shift-audit-title">{{ $shift['employee'] }} · {{ $shift['role'] }}</div><div class="shift-audit-meta">{{ $shift['start_at']->format('d-m-Y') }} · {{ $shift['time_label'] }} · {{ $shift['company'] }}</div></div><div>@foreach($shift['compliance_warnings'] as $warning)<span class="warning-chip"><i class="fas fa-exclamation-triangle"></i>{{ $warning }}</span>@endforeach @if(empty($shift['compliance_warnings']))<span class="break-chip"><i class="fas fa-check"></i>Clear</span>@endif</div></div><div class="shift-audit-body">
<div class="mb-2">@forelse($shift['planned_breaks'] as $break)<span class="break-chip mr-1"><i class="fas fa-mug-hot"></i>{{ substr($break->start_time,0,5) }} · {{ $break->duration_minutes }}m {{ $break->is_paid?'paid':'unpaid' }} <form class="d-inline" method="POST" action="{{ route('manager.schedule-compliance.breaks.destroy',$break->id) }}" onsubmit="return confirm('Remove this break?');">@csrf<input type="hidden" name="week" value="{{ $weekStart->toDateString() }}"><button class="btn btn-link btn-sm p-0 text-danger ml-1"><i class="fas fa-times"></i></button></form></span>@empty<span class="small text-muted">No planned break.</span>@endforelse</div>
<form class="break-form" method="POST" action="{{ route('manager.schedule-compliance.breaks.store') }}">@csrf<input type="hidden" name="week" value="{{ $weekStart->toDateString() }}"><input type="hidden" name="odoo_slot_id" value="{{ $shift['id'] }}"><div><label class="small">Start</label><input class="form-control form-control-sm" type="time" name="start_time" required></div><div><label class="small">Minutes</label><input class="form-control form-control-sm" type="number" name="duration_minutes" min="5" max="240" value="30" required></div><div><label class="small d-block">Type</label><label class="small mb-1"><input type="checkbox" name="is_paid" value="1"> Paid</label></div><div><label class="small">Note</label><input class="form-control form-control-sm" name="note" maxlength="500" placeholder="Meal break"></div><button class="btn btn-success btn-sm"><i class="fas fa-plus mr-1"></i>Add break</button></form>
</div></article>
@empty <div class="text-center text-muted py-5"><i class="fas fa-clipboard-check fa-3x text-gray-300 mb-3"></i><div>No Odoo shifts in this week.</div></div> @endforelse
</div></main></div></div>
@endsection
