@extends('layouts.admin.master')

@section('title', 'Team Calendar')

@section('css_after')
    <link rel="stylesheet" href="{{ asset('css/team-calendar.css') }}?v={{ filemtime(public_path('css/team-calendar.css')) }}">
@endsection

@section('content')
@php($canRequestLeave = $hasLeaveIdentity && !$leaveError && count($leaveTypes) > 0)
@php($unavailableVacationType = collect($leaveTypes)->first(fn($type) => !($type['can_request'] ?? true) && \Illuminate\Support\Str::contains(\Illuminate\Support\Str::lower($type['name']), ['paid time', 'annual', 'vacation'])))
@php($initialCalendarView = in_array(request()->query('view'), ['month', 'week', 'day'], true) ? request()->query('view') : null)
<main class="container-fluid team-calendar-page pb-4">
    <header class="tc-page-heading">
        <div><h1>Team Calendar</h1><p>View shifts, leave and events. Plan your time and stay updated.</p></div>
        <div class="tc-heading-actions">
            <div class="tc-heading-summary" aria-label="Month summary"><span><strong>{{ $summary['team_members'] }}</strong> people</span><span><strong>{{ $summary['shifts'] }}</strong> shifts</span><span><strong>{{ $summary['people_on_leave'] }}</strong> away</span></div>
            @if($canManageCalendar)<a href="{{ route('manager.leave-approvals.index') }}" class="tc-text-link"><i class="fas fa-user-check"></i> Leave approvals</a>@endif
        </div>
    </header>

    @if(session('success'))<div class="alert alert-success" data-calendar-success>{{ session('success') }}</div>@endif
    @if(session('calendar_event_success'))<div class="alert alert-success" data-event-success>{{ session('calendar_event_success') }}</div>@endif
    @if($errors->has('calendar_event'))<div class="alert alert-danger">{{ $errors->first('calendar_event') }}</div>@endif
    @if($calendarError)<div class="alert alert-warning">Team calendar data is temporarily unavailable: {{ $calendarError }}</div>@endif
    @if($leaveError)<div class="alert alert-warning">Leave requests are temporarily unavailable: {{ $leaveError }}</div>@endif

    <div class="tc-range-bar" id="leaveRangeBar" role="status" aria-live="polite">
        <div><strong id="leaveRangeTitle">Choose your leave dates</strong><span id="leaveRangeCopy">Select a start date, then an end date.</span></div>
        <div><button type="button" class="tc-plain-button" id="clearLeaveRange">Cancel</button><button type="button" class="tc-primary-button" id="continueLeaveRequest" disabled>Request leave</button></div>
    </div>

    <section class="tc-toolbar" aria-label="Calendar controls">
        <div class="tc-month-nav">
            <a class="tc-plain-button" id="calendarToday" href="{{ route('team-calendar.index',['month'=>now()->format('Y-m')]) }}">Today</a>
            <a class="tc-square-button" id="calendarPrevious" href="{{ route('team-calendar.index',['month'=>$previousMonth->format('Y-m')]) }}" aria-label="Previous month"><i class="fas fa-chevron-left"></i></a>
            <a class="tc-square-button" id="calendarNext" href="{{ route('team-calendar.index',['month'=>$nextMonth->format('Y-m')]) }}" aria-label="Next month"><i class="fas fa-chevron-right"></i></a>
            <label class="tc-month-picker" title="Jump to a month"><i class="far fa-calendar"></i><span id="calendarPeriodLabel" data-month-label="{{ $selectedMonth->format('F Y') }}">{{ $selectedMonth->format('F Y') }}</span><i class="fas fa-chevron-down"></i><input type="month" id="calendarMonthJump" value="{{ $selectedMonth->format('Y-m') }}" data-route="{{ route('team-calendar.index') }}" aria-label="Jump to a month"></label>
        </div>
        <div class="tc-view-switch" aria-label="Calendar view">
            <button type="button" class="is-active" data-calendar-view="month" aria-pressed="true">Month</button><button type="button" data-calendar-view="week" aria-pressed="false">Week</button><button type="button" data-calendar-view="day" aria-pressed="false">Day</button>
        </div>
        <div class="tc-toolbar-actions">
            <button type="button" class="tc-plain-button" id="toggleCalendarFilters" aria-expanded="false"><i class="fas fa-filter"></i> Filter</button>
            @if($canManageCalendar)<button type="button" class="tc-primary-button" id="addCalendarEvent"><i class="fas fa-plus"></i> Add event</button>@elseif($canRequestLeave)<button type="button" class="tc-primary-button" data-start-leave><i class="fas fa-plus"></i> Request leave</button>@endif
        </div>
        <div class="tc-filters" id="calendarFilters" hidden>
            <label class="tc-search"><i class="fas fa-search"></i><input id="teamCalendarSearch" type="search" placeholder="Find a colleague or event" aria-label="Search calendar"></label>
            <select id="teamCalendarCompany" aria-label="Filter by company"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company['id'] }}">{{ $company['name'] }}</option>@endforeach</select>
            <div class="tc-type-filters"><label class="is-shift"><input type="checkbox" value="shift" checked><span></span> Shifts</label><label class="is-leave"><input type="checkbox" value="leave" checked><span></span> Leave</label><label class="is-birthday"><input type="checkbox" value="birthday" checked><span></span> Birthdays</label><label class="is-event"><input type="checkbox" value="event" checked><span></span> Events</label></div>
        </div>
    </section>

    <div class="tc-workspace">
        <section class="tc-calendar-column">
            <div class="tc-legend"><span class="is-mine"><i></i> My shift</span><span class="is-team"><i></i> Team shift</span><span class="is-leave"><i></i> On leave</span><span class="is-birthday"><i></i> Birthday</span><span class="is-event"><i></i> Event</span></div>
            <div class="tc-calendar-shell" id="teamCalendar" role="grid" aria-label="Team calendar">
                <div class="tc-weekdays">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $weekday)<span>{{ $weekday }}</span>@endforeach</div>
                @foreach($weeks as $week)<div class="tc-week" role="row">@foreach($week as $day)
                    @php($selectable = $canRequestLeave && $day['date']->copy()->endOfDay()->gte(now()))
                    <div class="tc-day {{ !$day['is_current_month']?'is-outside':'' }} {{ $day['is_today']?'is-today':'' }}" role="gridcell" tabindex="0" data-calendar-day data-date="{{ $day['date_value'] }}" data-selectable="{{ $selectable?'1':'0' }}" aria-label="{{ $day['date']->format('l, d F Y') }}">
                        <div class="tc-day-head"><span class="tc-day-number">{{ $day['date']->day }}</span><span class="tc-event-count" data-event-count>{{ count($day['events']) > 2 ? count($day['events']) : '' }}</span></div>
                        <div class="tc-events">@foreach($day['events'] as $event)<button type="button" class="tc-event is-{{ $event['type'] }} {{ $event['is_mine']?'is-mine':'' }}" data-event="{{ base64_encode(json_encode($event)) }}" title="{{ $event['title'] }} · {{ $event['time'] }}"><strong>{{ $event['calendar_title'] ?? $event['title'] }}</strong><small>{{ $event['calendar_subtitle'] ?? $event['time'] }}</small></button>@endforeach</div>
                    </div>
                @endforeach</div>@endforeach
            </div>
            <div class="tc-timeline" id="calendarTimeline" hidden></div>
        </section>

        <aside class="tc-side-rail">
            <section class="tc-rail-card"><div class="tc-card-head"><div><h2>Who's on leave</h2><small>Now and upcoming</small></div><span>{{ count($teamOnLeave) }}</span></div><div class="tc-list">@forelse($teamOnLeave as $event)<article class="tc-list-with-status"><span class="tc-avatar">{{ strtoupper(substr($event['employee'],0,1)) }}</span><div><strong>{{ $event['employee'] }}</strong><small>{{ $event['date_range_label'] }} · Approved</small></div><span class="tc-rail-status {{ $event['timing_class'] }}">{{ $event['timing_label'] }}</span></article>@empty<div class="tc-empty"><i class="far fa-calendar-check"></i><strong>Everyone is available</strong><span>No current or upcoming approved leave in the visible calendar.</span></div>@endforelse</div></section>
            <section class="tc-rail-card"><div class="tc-card-head"><h2>My upcoming shifts</h2><a href="{{ route('employee.shifts.index') }}">View all</a></div><div class="tc-list">@forelse($myUpcomingShifts as $event)<article><i class="fas fa-briefcase is-shift"></i><div><strong>{{ $event['calendar_title'] }}</strong><small>{{ \Carbon\Carbon::parse($event['date'])->format('D, d M') }} · {{ $event['time'] }}</small></div></article>@empty<div class="tc-empty"><i class="far fa-clock"></i><strong>No shifts scheduled</strong><span>New published shifts will appear here.</span></div>@endforelse</div></section>
            <section class="tc-rail-card"><div class="tc-card-head"><div><h2>Events & birthdays</h2><small>Visible calendar</small></div><span>{{ count($upcomingMoments) }}</span></div><div class="tc-list tc-list-scroll">@forelse($upcomingMoments as $event)<article class="tc-list-with-status"><i class="fas {{ $event['icon'] }} is-{{ $event['type'] }}"></i><div><strong>{{ $event['calendar_title'] ?? $event['title'] }}</strong><small>{{ $event['type'] === 'birthday' ? 'Birthday' : $event['time'] }}</small></div><span class="tc-rail-status {{ $event['timing_class'] }}">{{ $event['timing_label'] }}</span></article>@empty<div class="tc-empty"><i class="far fa-calendar"></i><strong>No calendar moments</strong><span>No events or birthdays are available in the visible calendar.</span></div>@endforelse</div></section>
            @if($canRequestLeave)<button type="button" class="tc-leave-cta" data-start-leave><i class="far fa-calendar-check"></i> Request leave</button>@endif
        </aside>
    </div>
</main>

<div class="modal fade tc-modal" id="calendarEventDetails" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header"><div><span class="tc-modal-kicker" id="eventDetailType">Calendar item</span><h5 class="modal-title" id="eventDetailTitle">Event details</h5></div><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span>&times;</span></button></div><div class="modal-body"><dl class="tc-detail-list"><div><dt><i class="far fa-calendar"></i></dt><dd id="eventDetailDate"></dd></div><div><dt><i class="far fa-clock"></i></dt><dd id="eventDetailTime"></dd></div><div id="eventDetailCompanyRow"><dt><i class="far fa-building"></i></dt><dd id="eventDetailCompany"></dd></div><div id="eventDetailDescriptionRow"><dt><i class="far fa-sticky-note"></i></dt><dd id="eventDetailDescription"></dd></div></dl></div><div class="modal-footer"><form id="deleteEventForm" method="POST" class="mr-auto" hidden>@csrf<button class="btn btn-outline-danger" type="submit" onclick="return confirm('Delete this event?')">Delete</button></form><button type="button" class="btn btn-light" data-dismiss="modal">Close</button>@if($canManageCalendar)<button type="button" class="btn btn-primary" id="editCalendarEvent" hidden>Edit event</button>@endif</div></div></div></div>

@if($canManageCalendar)
<div class="modal fade tc-modal" id="calendarEventEditor" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header"><div><span class="tc-modal-kicker">Team calendar</span><h5 class="modal-title" id="eventEditorTitle">Add event</h5></div><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="POST" id="calendarEventForm" action="{{ route('team-calendar.events.store') }}">@csrf<input type="hidden" name="calendar_month" value="{{ $selectedMonth->format('Y-m') }}"><input type="hidden" name="event_form" value="1"><input type="hidden" name="calendar_event_id" id="calendarEventId"><div class="modal-body"><div class="form-group"><label for="calendarEventTitle">Event title</label><input class="form-control" id="calendarEventTitle" name="title" maxlength="120" required placeholder="Team building"></div><div class="form-row"><div class="form-group col-sm-6"><label for="calendarEventDate">Date</label><input class="form-control" type="date" id="calendarEventDate" name="schedule_date" required></div><div class="form-group col-sm-6"><label for="calendarEventCompany">Company</label><select class="form-control" id="calendarEventCompany" name="company_id" required><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company['id'] }}">{{ $company['name'] }}</option>@endforeach</select></div></div><div class="form-row"><div class="form-group col-sm-6"><label for="calendarEventStart">Start time <span>(optional)</span></label><input class="form-control" type="time" id="calendarEventStart" name="start_time"></div><div class="form-group col-sm-6"><label for="calendarEventEnd">End time <span>(optional)</span></label><input class="form-control" type="time" id="calendarEventEnd" name="end_time"></div></div><div class="form-group mb-0"><label for="calendarEventDescription">Description <span>(optional)</span></label><textarea class="form-control" id="calendarEventDescription" name="description" rows="3" maxlength="2000" placeholder="Location, agenda or other useful context"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary" id="eventEditorSubmit">Add event</button></div></form></div></div></div>
@endif

@if($canRequestLeave)
<div class="modal fade tc-modal tc-date-picker-modal" id="leaveDatePickerModal" tabindex="-1" role="dialog" aria-labelledby="leaveDatePickerTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content">
    <div class="modal-header"><div><span class="tc-modal-kicker">Step 1 of 2 · Dates</span><h5 class="modal-title" id="leaveDatePickerTitle">When will you be away?</h5><p>Select one day or a date range.</p></div><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span>&times;</span></button></div>
    <div class="modal-body"><div class="tc-picker-presets"><button type="button" data-picker-preset="today">Today</button><button type="button" data-picker-preset="tomorrow">Tomorrow</button><button type="button" data-picker-preset="next-week">Next work week</button></div><div class="tc-picker-toolbar"><button type="button" id="leavePickerPrevious" aria-label="Previous month"><i class="fas fa-chevron-left"></i></button><strong id="leavePickerMonth"></strong><button type="button" id="leavePickerNext" aria-label="Next month"><i class="fas fa-chevron-right"></i></button></div><div class="tc-picker-weekdays">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $weekday)<span>{{ $weekday }}</span>@endforeach</div><div class="tc-picker-grid" id="leavePickerGrid"></div><div class="tc-picker-hint"><i class="fas fa-info-circle"></i><span>Dates with team activity are marked with a dot. You can still request leave on those dates.</span></div></div>
    <div class="modal-footer tc-picker-footer"><div><span>Selected dates</span><strong id="leavePickerSummary">Choose a date</strong></div><button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary" id="leavePickerContinue" disabled>Continue to details <i class="fas fa-arrow-right ml-1"></i></button></div>
</div></div></div>
<div class="modal fade tc-modal" id="teamLeaveModal" tabindex="-1" role="dialog" aria-labelledby="teamLeaveModalTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header"><div><span class="tc-modal-kicker">Time away</span><h5 class="modal-title" id="teamLeaveModalTitle">Request leave</h5></div><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span>&times;</span></button></div><form method="POST" action="{{ route('employee.leave.store') }}" id="teamLeaveForm">@csrf<input type="hidden" name="return_to" value="team_calendar"><input type="hidden" name="calendar_month" value="{{ $selectedMonth->format('Y-m') }}"><div class="modal-body">
        @if(old('return_to') === 'team_calendar' && $errors->any())<div class="tc-modal-error" role="alert"><i class="fas fa-exclamation-circle"></i><div><strong>We couldn’t submit this request</strong><span>{{ $errors->first('leave_request') ?: $errors->first() }}</span></div></div>@endif
        <div class="tc-leave-summary"><i class="far fa-calendar-check"></i><span id="leaveModalSummary"></span></div>
        @if($unavailableVacationType)<div class="tc-allocation-notice"><i class="fas fa-umbrella-beach"></i><div><strong>Vacation is not currently available</strong><span>{{ $unavailableVacationType['name'] }} requires an active allocation in Odoo. Ask your manager or Time Off officer to grant the entitlement.</span></div></div>@endif
        <div class="form-group"><label for="teamLeaveType">Leave type</label><select class="form-control @error('leave_type_id') is-invalid @enderror" name="leave_type_id" id="teamLeaveType" required><option value="">Select leave type</option>@foreach($leaveTypes as $type)<option value="{{ $type['id'] }}" {{ ($type['can_request'] ?? true) ? '' : 'disabled' }} {{ (string)old('leave_type_id')===(string)$type['id']?'selected':'' }}>{{ $type['name'] }} · {{ $type['request_unit_label'] }}{{ ($type['can_request'] ?? true) ? '' : ' · No allocation' }}</option>@endforeach</select>@error('leave_type_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
            <div class="tc-leave-type-help" id="teamLeaveTypeHelp" hidden><i class="fas fa-info-circle"></i><div><strong id="teamLeaveTypeHelpTitle"></strong><p id="teamLeaveTypeHelpCopy"></p><small id="teamLeaveTypeHelpMeta"></small><span id="teamLeaveTypeHelpWarning" hidden></span></div></div>
            <details class="tc-leave-type-catalog"><summary><i class="far fa-question-circle"></i> Which leave type should I use?</summary><div>@foreach($leaveTypes as $type)<article class="{{ ($type['can_request'] ?? true) ? '' : 'is-unavailable' }}"><header><strong>{{ $type['name'] }}</strong><span>{{ ($type['can_request'] ?? true) ? $type['request_unit_label'] : 'No allocation' }}</span></header><p>{{ $type['usage_hint'] }}</p><small>{{ $type['approval_label'] }} · {{ $type['requires_allocation'] ? 'Uses an Odoo allocation' : 'No allocation required' }}</small></article>@endforeach<p class="tc-policy-note">These are typical uses. Your organisation’s HR policy and the configuration in Odoo are authoritative.</p></div></details>
        </div>
        <div class="form-row"><div class="form-group col-6" id="teamLeaveStartGroup"><label for="teamLeaveStart" id="teamLeaveStartLabel">From</label><input class="form-control @error('start_date') is-invalid @enderror" type="date" name="start_date" id="teamLeaveStart" min="{{ now()->toDateString() }}" value="{{ old('start_date') }}" required>@error('start_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group col-6" id="teamLeaveEndGroup"><label for="teamLeaveEnd">To</label><input class="form-control @error('end_date') is-invalid @enderror" type="date" name="end_date" id="teamLeaveEnd" min="{{ now()->toDateString() }}" value="{{ old('end_date') }}" required>@error('end_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
        <div class="tc-range-compatibility" id="teamLeaveRangeWarning" hidden><i class="fas fa-exclamation-triangle"></i><span>Hourly leave must start and end on the same date. Choose one date, or select a day-based leave type.</span></div>
        <div class="tc-unit-fields" id="teamLeaveHalfDayFields" hidden><div class="tc-unit-fields-head"><i class="far fa-clock"></i><div><strong>Choose half-day periods</strong><span>Specify whether the request begins and ends in the morning or afternoon.</span></div></div><div class="form-row"><div class="form-group col-6 mb-0"><label for="teamLeaveStartPeriod">Start period</label><select class="form-control" name="start_period" id="teamLeaveStartPeriod"><option value="am" {{ old('start_period','am')==='am'?'selected':'' }}>Morning</option><option value="pm" {{ old('start_period')==='pm'?'selected':'' }}>Afternoon</option></select></div><div class="form-group col-6 mb-0"><label for="teamLeaveEndPeriod">End period</label><select class="form-control" name="end_period" id="teamLeaveEndPeriod"><option value="am" {{ old('end_period')==='am'?'selected':'' }}>Morning</option><option value="pm" {{ old('end_period','pm')==='pm'?'selected':'' }}>Afternoon</option></select></div></div></div>
        <div class="tc-unit-fields" id="teamLeaveHourFields" hidden><div class="tc-unit-fields-head"><i class="far fa-clock"></i><div><strong>Choose the hours</strong><span>Hourly leave applies to one date only.</span></div></div><div class="form-row"><div class="form-group col-6 mb-0"><label for="teamLeaveStartTime">Start time</label><input class="form-control @error('start_hour') is-invalid @enderror" type="time" id="teamLeaveStartTime" step="900"><input type="hidden" name="start_hour" id="teamLeaveStartHour" value="{{ old('start_hour') }}">@error('start_hour')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group col-6 mb-0"><label for="teamLeaveEndTime">End time</label><input class="form-control @error('end_hour') is-invalid @enderror" type="time" id="teamLeaveEndTime" step="900"><input type="hidden" name="end_hour" id="teamLeaveEndHour" value="{{ old('end_hour') }}">@error('end_hour')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
        <div class="form-group mb-0"><label for="teamLeaveReason">Reason <span>(optional)</span></label><textarea class="form-control @error('reason') is-invalid @enderror" name="reason" id="teamLeaveReason" rows="3" maxlength="2000">{{ old('reason') }}</textarea>@error('reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary" id="teamLeaveSubmit"><i class="fas fa-paper-plane mr-1"></i> Submit request</button></div></form></div></div></div>
@endif

<div class="modal fade tc-modal" id="calendarSuccessModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content tc-success-content"><div class="modal-body"><span class="tc-success-icon"><i class="fas fa-check"></i></span><h5 id="calendarSuccessTitle">Request submitted</h5><p id="calendarSuccessCopy"></p><button type="button" class="btn btn-primary" data-dismiss="modal">Close</button></div></div></div></div>
@endsection

@section('js')
<script>
document.addEventListener('DOMContentLoaded', function () {
    const eventsByDate = @json($eventsByDate), leaveTypes = @json($leaveTypes), canManage = @json($canManageCalendar);
    const storeEventUrl = @json($canManageCalendar ? route('team-calendar.events.store') : ''), updateEventUrl = @json($canManageCalendar ? route('team-calendar.events.update', ['calendarEvent' => '__ID__']) : ''), deleteEventUrl = @json($canManageCalendar ? route('team-calendar.events.destroy', ['calendarEvent' => '__ID__']) : '');
    const cells=[...document.querySelectorAll('[data-calendar-day]')], viewButtons=[...document.querySelectorAll('[data-calendar-view]')], search=document.getElementById('teamCalendarSearch'), company=document.getElementById('teamCalendarCompany'), typeInputs=[...document.querySelectorAll('.tc-type-filters input')], monthCalendar=document.getElementById('teamCalendar'), timeline=document.getElementById('calendarTimeline'), rangeBar=document.getElementById('leaveRangeBar'), startInput=document.getElementById('teamLeaveStart'), endInput=document.getElementById('teamLeaveEnd');
    let selectedDate=@json($selectedCalendarDate->toDateString()), view=@json($initialCalendarView)||sessionStorage.getItem('teamCalendarView')||'month', rangeMode=false, rangeStart=startInput?.value||'', rangeEnd=endInput?.value||'', activeEvent=null;
    let pickerMonth=new Date(),pickerStart='',pickerEnd='';
    const parseDate=v=>new Date(v+'T12:00:00'), isoDate=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'), dateLabel=(v,o={weekday:'long',day:'numeric',month:'long',year:'numeric'})=>new Intl.DateTimeFormat('en-GB',o).format(parseDate(v)), escapeHtml=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])), decodeEvent=v=>JSON.parse(decodeURIComponent(escape(atob(v))));
    const filterState=()=>({q:(search?.value||'').trim().toLowerCase(),company:company?.value||'',types:new Set(typeInputs.filter(i=>i.checked).map(i=>i.value))});
    const visibleEvents=date=>{const f=filterState();return(eventsByDate[date]||[]).filter(e=>f.types.has(e.type)&&(!f.company||String(e.company_id)===f.company)&&(!f.q||[e.title,e.employee,e.company,e.detail].join(' ').toLowerCase().includes(f.q)));};
    const decimalHourToTime=value=>{if(value===''||value===null||Number.isNaN(Number(value)))return'';const total=Math.round(Number(value)*60);if(total>=1440)return'23:59';const hours=Math.floor(total/60),minutes=total%60;return String(hours).padStart(2,'0')+':'+String(minutes).padStart(2,'0');};
    const timeToDecimal=value=>{if(!value)return'';const [hours,minutes]=value.split(':').map(Number);return (hours+minutes/60).toFixed(2);};
    function renderLeavePicker(){const grid=document.getElementById('leavePickerGrid');if(!grid)return;const first=new Date(pickerMonth.getFullYear(),pickerMonth.getMonth(),1),offset=(first.getDay()+6)%7,daysInMonth=new Date(pickerMonth.getFullYear(),pickerMonth.getMonth()+1,0).getDate(),cellCount=Math.ceil((offset+daysInMonth)/7)*7,start=new Date(first);start.setDate(first.getDate()-offset);document.getElementById('leavePickerMonth').textContent=new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(first);grid.replaceChildren();const today=isoDate(new Date()),rangeEndValue=pickerEnd||pickerStart;for(let index=0;index<cellCount;index++){const date=new Date(start);date.setDate(start.getDate()+index);const value=isoDate(date),button=document.createElement('button');button.type='button';button.dataset.pickerDate=value;button.disabled=value<today;button.className=(date.getMonth()!==pickerMonth.getMonth()?'is-outside ':'')+(value===today?'is-today ':'')+(pickerStart&&value>=pickerStart&&value<=rangeEndValue?'is-in-range ':'')+(value===pickerStart?'is-range-start ':'')+(value===rangeEndValue?'is-range-end ':'');button.innerHTML='<span>'+date.getDate()+'</span>'+((eventsByDate[value]||[]).length?'<i aria-label="Team activity"></i>':'');button.setAttribute('aria-label',dateLabel(value));button.addEventListener('click',()=>selectPickerDate(value));grid.appendChild(button);}renderPickerSummary();}
    function renderPickerSummary(){const summary=document.getElementById('leavePickerSummary'),continueButton=document.getElementById('leavePickerContinue');if(!summary)return;if(!pickerStart){summary.textContent='Choose a date';continueButton.disabled=true;return;}const end=pickerEnd||pickerStart,days=Math.round((parseDate(end)-parseDate(pickerStart))/86400000)+1;summary.textContent=dateLabel(pickerStart,{day:'numeric',month:'short',year:'numeric'})+(end!==pickerStart?' – '+dateLabel(end,{day:'numeric',month:'short',year:'numeric'}):'')+' · '+days+' day'+(days===1?'':'s');continueButton.disabled=false;}
    function selectPickerDate(value){if(!pickerStart||pickerEnd){pickerStart=value;pickerEnd='';}else if(value<pickerStart){pickerEnd=pickerStart;pickerStart=value;}else pickerEnd=value;renderLeavePicker();}
    function openLeaveDatePicker(){const initial=rangeStart||(@json(now()->toDateString()));pickerStart=rangeStart;pickerEnd=rangeEnd;pickerMonth=new Date(initial+'T12:00:00');pickerMonth.setDate(1);renderLeavePicker();$('#leaveDatePickerModal').modal('show');}
    function confirmLeaveDates(){if(!pickerStart)return;rangeStart=pickerStart;rangeEnd=pickerEnd||pickerStart;rangeMode=false;rangeRender();const picker=$('#leaveDatePickerModal');let opened=false;const openDetails=()=>{if(opened)return;opened=true;openLeave();};picker.one('hidden.bs.modal',openDetails);picker.modal('hide');window.setTimeout(openDetails,400);}
    function applyPickerPreset(preset){const today=new Date();let start=new Date(today),end=new Date(today);if(preset==='tomorrow'){start.setDate(start.getDate()+1);end=new Date(start);}else if(preset==='next-week'){const untilMonday=((8-today.getDay())%7)||7;start.setDate(today.getDate()+untilMonday);end=new Date(start);end.setDate(start.getDate()+4);}pickerStart=isoDate(start);pickerEnd=isoDate(end);pickerMonth=new Date(start.getFullYear(),start.getMonth(),1);renderLeavePicker();}
    function renderLeaveTypeHelp(){const select=document.getElementById('teamLeaveType'),panel=document.getElementById('teamLeaveTypeHelp'),submit=document.getElementById('teamLeaveSubmit'),halfFields=document.getElementById('teamLeaveHalfDayFields'),hourFields=document.getElementById('teamLeaveHourFields'),rangeWarning=document.getElementById('teamLeaveRangeWarning');if(!select||!panel)return;const type=leaveTypes.find(item=>String(item.id)===select.value),isHalf=type?.request_unit==='half_day',isHour=type?.request_unit==='hour',isMultiDay=!!(startInput?.value&&endInput?.value&&startInput.value!==endInput.value),rangeIncompatible=isHour&&isMultiDay;panel.hidden=!type;halfFields.hidden=!isHalf;hourFields.hidden=!isHour;rangeWarning.hidden=!rangeIncompatible;document.getElementById('teamLeaveStartPeriod').disabled=!isHalf;document.getElementById('teamLeaveEndPeriod').disabled=!isHalf;document.getElementById('teamLeaveStartHour').disabled=!isHour;document.getElementById('teamLeaveEndHour').disabled=!isHour;document.getElementById('teamLeaveStartTime').required=isHour;document.getElementById('teamLeaveEndTime').required=isHour;if(!type){if(submit)submit.disabled=false;return;}document.getElementById('teamLeaveTypeHelpTitle').textContent=type.name;document.getElementById('teamLeaveTypeHelpCopy').textContent=type.usage_hint;document.getElementById('teamLeaveTypeHelpMeta').textContent=[type.request_unit_label,type.approval_label,type.requires_allocation?'Allocation required':'No allocation required'].join(' · ');const warning=document.getElementById('teamLeaveTypeHelpWarning');warning.hidden=!type.availability_note;warning.textContent=type.availability_note||'';panel.classList.toggle('is-unavailable',type.can_request===false);if(submit)submit.disabled=type.can_request===false||rangeIncompatible;}
    function selectDate(date){selectedDate=date;cells.forEach(c=>c.classList.toggle('is-selected',c.dataset.date===date));if(view!=='month')renderTimeline();}
    function applyFilters(){cells.forEach(cell=>{const visible=visibleEvents(cell.dataset.date);[...cell.querySelectorAll('.tc-event')].forEach(button=>{const event=decodeEvent(button.dataset.event);button.hidden=!visible.some(item=>item.type===event.type&&item.title===event.title&&item.time===event.time);});const count=cell.querySelector('[data-event-count]');if(count)count.textContent=visible.length>2?visible.length:'';});if(view!=='month')renderTimeline();}
    function rangeRender(){const end=rangeEnd||rangeStart;cells.forEach(c=>{const d=c.dataset.date;c.classList.toggle('is-in-range',!!rangeStart&&d>=rangeStart&&d<=end);c.classList.toggle('is-range-start',d===rangeStart);c.classList.toggle('is-range-end',d===end);});rangeBar.classList.toggle('is-visible',rangeMode);document.getElementById('leaveRangeTitle').textContent=!rangeStart?'Choose your leave dates':rangeEnd?'Leave range selected':'Now choose the end date';document.getElementById('leaveRangeCopy').textContent=!rangeStart?'Select a start date, then an end date.':rangeEnd?dateLabel(rangeStart,{day:'numeric',month:'short',year:'numeric'})+' – '+dateLabel(rangeEnd,{day:'numeric',month:'short',year:'numeric'}):'Starts '+dateLabel(rangeStart,{day:'numeric',month:'short',year:'numeric'});document.getElementById('continueLeaveRequest').disabled=!rangeStart;}
    function renderLeaveDateFields(){if(!startInput||!endInput)return;const singleDay=!!startInput.value&&startInput.value===endInput.value,startGroup=document.getElementById('teamLeaveStartGroup'),endGroup=document.getElementById('teamLeaveEndGroup'),label=document.getElementById('teamLeaveStartLabel');startGroup.classList.toggle('col-6',!singleDay);startGroup.classList.toggle('col-12',singleDay);endGroup.hidden=singleDay;label.textContent=singleDay?'Date':'From';document.getElementById('leaveModalSummary').textContent=singleDay?dateLabel(startInput.value):dateLabel(startInput.value)+' – '+dateLabel(endInput.value);}
    function beginRange(){rangeMode=true;rangeStart='';rangeEnd='';rangeRender();document.querySelector('[data-selectable="1"]')?.focus();} function chooseRange(date){if(!rangeStart||rangeEnd){rangeStart=date;rangeEnd='';}else if(date<rangeStart){rangeEnd=rangeStart;rangeStart=date;}else rangeEnd=date;rangeRender();} function openLeave(){if(!rangeStart)rangeStart=selectedDate;if(!rangeEnd)rangeEnd=rangeStart;startInput.value=rangeStart;endInput.value=rangeEnd;renderLeaveDateFields();renderLeaveTypeHelp();$('#teamLeaveModal').modal('show');}
    function weekDates(){const date=parseDate(selectedDate),start=new Date(date),mondayOffset=(date.getDay()+6)%7;start.setDate(date.getDate()-mondayOffset);return Array.from({length:view==='week'?7:1},(_,i)=>{const d=new Date(view==='week'?start:date);d.setDate(d.getDate()+i);return isoDate(d);});}
    function updatePeriodLabel(dates=null){const label=document.getElementById('calendarPeriodLabel');if(view==='month'){label.textContent=label.dataset.monthLabel;return;}const values=dates||weekDates();if(view==='day'){label.textContent=dateLabel(values[0],{weekday:'short',day:'numeric',month:'short',year:'numeric'});return;}const start=parseDate(values[0]),end=parseDate(values[values.length-1]),sameMonth=start.getMonth()===end.getMonth()&&start.getFullYear()===end.getFullYear(),sameYear=start.getFullYear()===end.getFullYear();label.textContent=sameMonth?start.getDate()+'–'+end.getDate()+' '+dateLabel(values[0],{month:'short',year:'numeric'}):sameYear?start.getDate()+' '+dateLabel(values[0],{month:'short'})+'–'+end.getDate()+' '+dateLabel(values[values.length-1],{month:'short',year:'numeric'}):dateLabel(values[0],{day:'numeric',month:'short',year:'numeric'})+'–'+dateLabel(values[values.length-1],{day:'numeric',month:'short',year:'numeric'});}
    function eventMinutes(event){const match=(event.start_time||event.time||'').match(/(\d{1,2}):(\d{2})\s*(AM|PM)?/i);if(!match)return null;let h=+match[1],m=+match[2];if(match[3]?.toUpperCase()==='PM'&&h<12)h+=12;if(match[3]?.toUpperCase()==='AM'&&h===12)h=0;return h*60+m;}
    function timelineEventButton(event,className){return'<button class="'+className+' is-'+event.type+(event.is_mine?' is-mine':'')+'" data-timeline-event="'+escapeHtml(JSON.stringify(event))+'"><strong>'+escapeHtml(event.calendar_title||event.title)+'</strong><small>'+escapeHtml(event.calendar_subtitle||event.time||'All day')+'</small></button>';}
    function arrangeTimedEvents(events){const items=events.map(event=>{const start=eventMinutes(event),parsedEnd=event.end_time?eventMinutes({start_time:event.end_time}):null;return{event,start,end:Math.max(start+15,parsedEnd??start+60),lane:0,lanes:1};}).sort((a,b)=>a.start-b.start||a.end-b.end),groups=[];let group=null;items.forEach(item=>{if(!group||item.start>=group.maxEnd){group={items:[],maxEnd:item.end};groups.push(group);}group.items.push(item);group.maxEnd=Math.max(group.maxEnd,item.end);});groups.forEach(current=>{const laneEnds=[];current.items.forEach(item=>{let lane=laneEnds.findIndex(end=>end<=item.start);if(lane<0)lane=laneEnds.length;item.lane=lane;laneEnds[lane]=item.end;});current.items.forEach(item=>item.lanes=laneEnds.length);});return items;}
    function renderTimeline(){
        const dates=weekDates(),startHour=7,endHour=20,rowHeight=54;
        const timedByDate=dates.map(date=>arrangeTimedEvents(visibleEvents(date).filter(event=>eventMinutes(event)!==null)));
        updatePeriodLabel(dates);timeline.classList.toggle('is-day-view',view==='day');
        let html='<div class="tc-time-head" style="--days:'+dates.length+'"><span></span>'+dates.map(d=>'<button type="button" data-timeline-date="'+d+'"><small>'+dateLabel(d,{weekday:'short'})+'</small><strong>'+dateLabel(d,{day:'numeric',month:'short'})+'</strong></button>').join('')+'</div>';
        html+='<div class="tc-all-day-row" style="--days:'+dates.length+'"><span>All day</span>'+dates.map(date=>'<div class="tc-all-day-cell">'+visibleEvents(date).filter(event=>eventMinutes(event)===null).map(event=>timelineEventButton(event,'tc-all-day-event')).join('')+'</div>').join('')+'</div>';
        html+='<div class="tc-time-body" style="--days:'+dates.length+'">';
        for(let hour=startHour;hour<=endHour;hour++)html+='<span class="tc-time-label" style="grid-row:'+(hour-startHour+1)+'">'+(hour>12?hour-12:hour)+':00 '+(hour>=12?'PM':'AM')+'</span>';
        dates.forEach((date,col)=>{html+='<div class="tc-time-column" style="grid-column:'+(col+2)+'"></div>';timedByDate[col].forEach(item=>{const event=item.event,top=((item.start-startHour*60)/60)*rowHeight+4,duration=Math.max(38,((item.end-item.start)/60)*rowHeight-6),baseFraction=(col+item.lane/item.lanes)/dates.length,leftPercent=(baseFraction*100).toFixed(6),leftPixels=(64-baseFraction*60).toFixed(3),widthPercent=(100/(dates.length*item.lanes)).toFixed(6),widthPixels=(60/(dates.length*item.lanes)+8).toFixed(3),detail=event.detail&&event.detail!=='Team event'?event.detail:event.company||'';html+='<button class="tc-time-event is-'+event.type+(event.is_mine?' is-mine':'')+'" style="--event-left:calc('+leftPercent+'% + '+leftPixels+'px);--event-width:calc('+widthPercent+'% - '+widthPixels+'px);top:'+Math.max(4,top)+'px;height:'+duration+'px" data-timeline-event="'+escapeHtml(JSON.stringify(event))+'"><strong>'+escapeHtml(event.calendar_title||event.title)+'</strong><small>'+escapeHtml(event.time||'')+'</small><span class="tc-time-detail">'+escapeHtml(detail)+'</span></button>';});});
        const todayIndex=dates.indexOf(isoDate(new Date())),now=new Date(),nowMinutes=now.getHours()*60+now.getMinutes();if(todayIndex>=0&&nowMinutes>=startHour*60&&nowMinutes<=endHour*60)html+='<div class="tc-now-line" style="top:'+((nowMinutes-startHour*60)/60*rowHeight)+'px"><span>Now</span></div>';
        timeline.innerHTML=html+'</div>';timeline.querySelectorAll('[data-timeline-event]').forEach(button=>button.onclick=()=>openDetails(JSON.parse(button.dataset.timelineEvent)));timeline.querySelectorAll('[data-timeline-date]').forEach(button=>button.onclick=()=>{selectedDate=button.dataset.timelineDate;if(view==='week')setView('day');});
    }
    function setView(next){view=['month','week','day'].includes(next)?next:'month';sessionStorage.setItem('teamCalendarView',view);monthCalendar.hidden=view!=='month';timeline.hidden=view==='month';viewButtons.forEach(b=>{const active=b.dataset.calendarView===view;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',active?'true':'false');});const previous=document.getElementById('calendarPrevious'),nextButton=document.getElementById('calendarNext'),unit=view.charAt(0).toUpperCase()+view.slice(1);previous.setAttribute('aria-label','Previous '+view);previous.title='Previous '+view;nextButton.setAttribute('aria-label','Next '+view);nextButton.title='Next '+view;document.getElementById('calendarToday').title='Go to current '+view;if(view!=='month')renderTimeline();else updatePeriodLabel();}
    function navigateToDate(target){const value=isoDate(target);if(cells.some(cell=>cell.dataset.date===value)){selectDate(value);return;}const route=document.getElementById('calendarMonthJump').dataset.route;location.href=route+'?month='+value.slice(0,7)+'&day='+value+'&view='+view;}
    function moveVisiblePeriod(direction){const target=parseDate(selectedDate);target.setDate(target.getDate()+direction*(view==='week'?7:1));navigateToDate(target);}
    function eventSourceInput(form,value){let input=form.querySelector('[name="event_source"]');if(!input){input=document.createElement('input');input.type='hidden';input.name='event_source';form.appendChild(input);}input.value=value||'calendar_event';}
    function openDetails(event){activeEvent=event;document.getElementById('eventDetailType').textContent=event.type==='shift'?(event.is_mine?'My shift':'Team shift'):event.type;document.getElementById('eventDetailTitle').textContent=event.title;document.getElementById('eventDetailDate').textContent=dateLabel(event.date);document.getElementById('eventDetailTime').textContent=event.time||'All day';document.getElementById('eventDetailCompany').textContent=event.company||'';document.getElementById('eventDetailCompanyRow').hidden=!event.company;document.getElementById('eventDetailDescription').textContent=event.detail||'';document.getElementById('eventDetailDescriptionRow').hidden=!event.detail;const editable=canManage&&event.type==='event'&&event.id,edit=document.getElementById('editCalendarEvent'),del=document.getElementById('deleteEventForm');if(edit)edit.hidden=!editable;if(del){del.hidden=!editable;del.action=editable?deleteEventUrl.replace('__ID__',event.id):'';eventSourceInput(del,event.source);}$('#calendarEventDetails').modal('show');}
    function openEditor(event=null){const form=document.getElementById('calendarEventForm');form.reset();form.action=event?.id?updateEventUrl.replace('__ID__',event.id):storeEventUrl;eventSourceInput(form,event?.source);document.getElementById('calendarEventId').value=event?.id||'';document.getElementById('eventEditorTitle').textContent=event?.id?'Edit event':'Add event';document.getElementById('eventEditorSubmit').textContent=event?.id?'Save changes':'Add event';document.getElementById('calendarEventTitle').value=event?.title||'';document.getElementById('calendarEventDate').value=event?.date||selectedDate;document.getElementById('calendarEventCompany').value=event?.company_id||'';document.getElementById('calendarEventStart').value=event?.start_time||'';document.getElementById('calendarEventEnd').value=event?.end_time||'';document.getElementById('calendarEventDescription').value=event?.detail==='Team event'?'':event?.detail||'';$('#calendarEventDetails').modal('hide');$('#calendarEventEditor').modal('show');}
    cells.forEach(cell=>{cell.addEventListener('click',e=>{if(e.target.closest('.tc-event'))return;selectDate(cell.dataset.date);if(rangeMode&&cell.dataset.selectable==='1')chooseRange(cell.dataset.date);});cell.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();cell.click();}});cell.querySelectorAll('.tc-event').forEach(button=>button.onclick=()=>openDetails(decodeEvent(button.dataset.event)));});viewButtons.forEach(b=>b.onclick=()=>setView(b.dataset.calendarView));search?.addEventListener('input',applyFilters);company?.addEventListener('change',applyFilters);typeInputs.forEach(i=>i.addEventListener('change',applyFilters));
    document.getElementById('calendarPrevious').addEventListener('click',event=>{if(view==='month')return;event.preventDefault();moveVisiblePeriod(-1);});document.getElementById('calendarNext').addEventListener('click',event=>{if(view==='month')return;event.preventDefault();moveVisiblePeriod(1);});document.getElementById('calendarToday').addEventListener('click',event=>{if(view==='month')return;event.preventDefault();navigateToDate(new Date());});
    document.getElementById('toggleCalendarFilters').onclick=function(){const panel=document.getElementById('calendarFilters'),opening=panel.hidden;panel.hidden=!opening;this.setAttribute('aria-expanded',opening?'true':'false');};document.getElementById('calendarMonthJump').onchange=e=>{if(e.target.value)location.href=e.target.dataset.route+'?month='+encodeURIComponent(e.target.value);};document.querySelectorAll('[data-start-leave]').forEach(b=>b.onclick=openLeaveDatePicker);document.getElementById('leavePickerPrevious')?.addEventListener('click',()=>{pickerMonth.setMonth(pickerMonth.getMonth()-1);renderLeavePicker();});document.getElementById('leavePickerNext')?.addEventListener('click',()=>{pickerMonth.setMonth(pickerMonth.getMonth()+1);renderLeavePicker();});document.querySelectorAll('[data-picker-preset]').forEach(button=>button.addEventListener('click',()=>applyPickerPreset(button.dataset.pickerPreset)));document.getElementById('leavePickerContinue')?.addEventListener('click',confirmLeaveDates);document.getElementById('clearLeaveRange').onclick=()=>{rangeMode=false;rangeStart='';rangeEnd='';rangeRender();};document.getElementById('continueLeaveRequest')?.addEventListener('click',openLeave);document.getElementById('teamLeaveType')?.addEventListener('change',renderLeaveTypeHelp);startInput?.addEventListener('change',()=>{rangeStart=startInput.value;if(endInput.value<rangeStart)endInput.value=rangeStart;rangeEnd=endInput.value||rangeStart;rangeRender();renderLeaveTypeHelp();});endInput?.addEventListener('change',()=>{rangeEnd=endInput.value;rangeRender();renderLeaveTypeHelp();});document.getElementById('teamLeaveForm')?.addEventListener('submit',()=>{document.getElementById('teamLeaveStartHour').value=timeToDecimal(document.getElementById('teamLeaveStartTime').value);document.getElementById('teamLeaveEndHour').value=timeToDecimal(document.getElementById('teamLeaveEndTime').value);});document.getElementById('addCalendarEvent')?.addEventListener('click',()=>openEditor());document.getElementById('editCalendarEvent')?.addEventListener('click',()=>openEditor(activeEvent));
    startInput?.addEventListener('change',()=>{if(document.getElementById('teamLeaveEndGroup').hidden){endInput.value=startInput.value;rangeEnd=rangeStart=startInput.value;}renderLeaveDateFields();});endInput?.addEventListener('change',renderLeaveDateFields);
    const leaveStepLabel=document.querySelector('#teamLeaveModal .tc-modal-kicker');if(leaveStepLabel)leaveStepLabel.textContent='Step 2 of 2 · Leave details';
    const leaveStartTime=document.getElementById('teamLeaveStartTime'),leaveEndTime=document.getElementById('teamLeaveEndTime');if(leaveStartTime)leaveStartTime.value=decimalHourToTime(document.getElementById('teamLeaveStartHour').value);if(leaveEndTime)leaveEndTime.value=decimalHourToTime(document.getElementById('teamLeaveEndHour').value);selectDate(selectedDate);applyFilters();rangeRender();setView(view);renderLeaveTypeHelp();@if($errors->any() && old('return_to') === 'team_calendar') openLeave(); @endif @if(old('event_form') === '1') openEditor({id:@json(old('calendar_event_id')),title:@json(old('title')),date:@json(old('schedule_date')),company_id:@json(old('company_id')),start_time:@json(old('start_time')),end_time:@json(old('end_time')),detail:@json(old('description'))}); @endif const success=document.querySelector('[data-calendar-success],[data-event-success]');if(success){document.getElementById('calendarSuccessTitle').textContent=success.hasAttribute('data-calendar-success')?'Leave request submitted':'Calendar updated';document.getElementById('calendarSuccessCopy').textContent=success.textContent.trim();success.hidden=true;$('#calendarSuccessModal').modal('show');}
});
</script>
@if(old('event_form') === '1')
<script>
document.addEventListener('DOMContentLoaded', function () {
    const form = document.getElementById('calendarEventForm');
    if (!form) return;
    let input = form.querySelector('[name="event_source"]');
    if (!input) { input = document.createElement('input'); input.type = 'hidden'; input.name = 'event_source'; form.appendChild(input); }
    input.value = @json(old('event_source', 'calendar_event'));
});
</script>
@endif
@endsection
